### ISSUE TITLE
yaml.composer.ComposerError: found undefined alias 'operations-openstack-mandatory-series'

### ISSUE THREAD

**Issue by esunar** [esunar/test4#102]
$ juju-lint -c /snap/juju-lint/current/contrib/kubernetes.yaml generated/kubernetes/bundle.yaml
2021-09-30 11:53:51 [INFO] juju-lint version 1.0.2.dev52+gea337d4 starting...
        * Config directory: /home/ubuntu/.config/juju-lint
        * Rules file: /snap/juju-lint/current/contrib/kubernetes.yaml
        * Log level: info

Traceback (most recent call last):
  File "/snap/juju-lint/42/bin/juju-lint", line 33, in <module>
    sys.exit(load_entry_point('jujulint==1.0.2.dev52+gea337d4', 'console_scripts', 'juju-lint')())
  File "/snap/juju-lint/42/lib/python3.6/site-packages/jujulint/cli.py", line 168, in main
    cli.audit_file(manual_file)
  File "/snap/juju-lint/42/lib/python3.6/site-packages/jujulint/cli.py", line 94, in audit_file
    linter.read_rules()
  File "/snap/juju-lint/42/lib/python3.6/site-packages/jujulint/lint.py", line 125, in read_rules
    self.lint_rules = self._process_includes_in_rules(raw_rules_txt)
  File "/snap/juju-lint/42/lib/python3.6/site-packages/jujulint/lint.py", line 1065, in _process_includes_in_rules
    return yaml.safe_load("\n".join(collector))
  File "/snap/juju-lint/42/lib/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/snap/juju-lint/42/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/snap/juju-lint/42/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/snap/juju-lint/42/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/snap/juju-lint/42/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/snap/juju-lint/42/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/snap/juju-lint/42/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/snap/juju-lint/42/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/snap/juju-lint/42/lib/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/snap/juju-lint/42/lib/python3.6/site-packages/yaml/composer.py", line 69, in compose_node
    % anchor, event.start_mark)
yaml.composer.ComposerError: found undefined alias 'operations-openstack-mandatory-series'
  in "<unicode string>", line 67, column 4:
     - *operations-openstack-mandatory- ... 
       ^

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2021-09-30T11:55:00Z
 * owner: [nobuto](https://launchpad.net/~nobuto)
 * assignee: [None](https://launchpad.net/~None)
 * duplicate of: #153
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1945635)

**Comment by esunar** [comment]
(by [camille.rodriguez](https://launchpad.net/~camille.rodriguez))
Seeing the same issue today. juju lint version 1.0.2.dev67+g8d75f21


$ juju-lint -c /snap/juju-lint/current/contrib/kubernetes.yaml juju-status-20220415.yaml 
2022-04-15 16:54:28 [INFO] juju-lint version 1.0.2.dev67+g8d75f21 starting...
        * Config directory: /home/k8s/.config/juju-lint
        * Rules file: /snap/juju-lint/current/contrib/kubernetes.yaml
        * Log level: info

Traceback (most recent call last):
  File "/snap/juju-lint/47/bin/juju-lint", line 33, in <module>
    sys.exit(load_entry_point('jujulint==1.0.2.dev67+g8d75f21', 'console_scripts', 'juju-lint')())
  File "/snap/juju-lint/47/lib/python3.6/site-packages/jujulint/cli.py", line 168, in main
    cli.audit_file(manual_file)
  File "/snap/juju-lint/47/lib/python3.6/site-packages/jujulint/cli.py", line 94, in audit_file
    linter.read_rules()
  File "/snap/juju-lint/47/lib/python3.6/site-packages/jujulint/lint.py", line 126, in read_rules
    self.lint_rules = self._process_includes_in_rules(raw_rules_txt)
  File "/snap/juju-lint/47/lib/python3.6/site-packages/jujulint/lint.py", line 1148, in _process_includes_in_rules
    return yaml.safe_load("\n".join(collector))
  File "/snap/juju-lint/47/lib/python3.6/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/snap/juju-lint/47/lib/python3.6/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/snap/juju-lint/47/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/snap/juju-lint/47/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/snap/juju-lint/47/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/snap/juju-lint/47/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/snap/juju-lint/47/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/snap/juju-lint/47/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/snap/juju-lint/47/lib/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/snap/juju-lint/47/lib/python3.6/site-packages/yaml/composer.py", line 69, in compose_node
    % anchor, event.start_mark)
yaml.composer.ComposerError: found undefined alias 'operations-openstack-mandatory-series'
  in "<unicode string>", line 69, column 4:
     - *operations-openstack-mandatory- ... 
       ^
