### ISSUE TITLE
Parsing for charm name does not properly handle charm hub sources

### ISSUE THREAD

**Issue by esunar** [esunar/test4#106]
When using charms from charm hub the exported format for json contains more information then the regular expression can handle.

   ch:amd64/bionic/juju-lint-1

INFO:root:[/var/snap/juju-lint/common/juju-status.json] Linting manual file...
Traceback (most recent call last):
  File "/snap/juju-lint/42/bin/juju-lint", line 33, in <module>
    sys.exit(load_entry_point('jujulint==1.0.2.dev52+gea337d4', 'console_scripts', 'juju-lint')())
  File "/snap/juju-lint/42/lib/python3.6/site-packages/jujulint/cli.py", line 166, in main
    cli.audit_file(manual_file, cloud_type=manual_type)
  File "/snap/juju-lint/42/lib/python3.6/site-packages/jujulint/cli.py", line 96, in audit_file
    linter.lint_yaml_file(filename)
  File "/snap/juju-lint/42/lib/python3.6/site-packages/jujulint/lint.py", line 983, in lint_yaml_file
    return self.do_lint(parsed_yaml)
  File "/snap/juju-lint/42/lib/python3.6/site-packages/jujulint/lint.py", line 996, in do_lint
    self.map_charms(parsed_yaml[applications])
  File "/snap/juju-lint/42/lib/python3.6/site-packages/jujulint/lint.py", line 754, in map_charms
    charm_name = utils.extract_charm_name(applications[app]["charm"])
  File "/snap/juju-lint/42/lib/python3.6/site-packages/jujulint/util.py", line 83, in extract_charm_name
    raise InvalidCharmNameError("charm name '{}' is invalid".format(charm))
jujulint.util.InvalidCharmNameError: charm name 'ch:amd64/bionic/juju-lint-1' is invalid

Modify /snap/juju-lint/42/lib/python3.6/site-packages/jujulint/util.py

def extract_charm_name(charm):
    """Extract the charm name using regex."""
    match = re.match(
        r"^(?:\w+:)?(?:~[\w\.-]+/)?(?:\w+/)*([a-zA-Z0-9-]+?)(?:-\d+)?$", charm
                                           ^ change from ? to *
    )
    if not match:
        raise InvalidCharmNameError("charm name '{}' is invalid 2".format(charm))
    return match.group(1)

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2021-11-15T13:35:59Z
 * owner: [sbparke](https://launchpad.net/~sbparke)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1950980)

**Comment by esunar** [comment]
(by [sbparke](https://launchpad.net/~sbparke))
Replicate with deployment of juju-lint from charm hub into model you are going to lint.

  https://charmhub.io/juju-lint

**Comment by esunar** [comment]
(by [elmo](https://launchpad.net/~elmo))
Fixed in https://code.launchpad.net/~sbparke/juju-lint/+git/juju-lint-1/+merge/411887
