### ISSUE TITLE
Getting many KeyError errors during spaces checks

### ISSUE THREAD

**Issue by esunar** [esunar/test4#123]
Running juju-lint on an exported bundle I get more than a dozen of these:

Exception caught during space check; please check space by hand. Traceback (most recent call last):
  File "/snap/juju-lint/current/lib/python3.8/site-packages/jujulint/lint.py", line 696, in check_spaces
    self._handle_space_mismatch(
  File "/snap/juju-lint/current/lib/python3.8/site-packages/jujulint/lint.py", line 725, in _handle_space_mismatch
    mismatch_relation = mismatch.get_charm_relation(self.model.app_to_charm)
  File "/snap/juju-lint/current/lib/python3.8/site-packages/jujulint/check_spaces.py", line 63, in get_charm_relation
    charm2 = app_to_charm_map[app2]
KeyError: 'prometheus'

It looks like these are related to CMR relations since all the applications mentioned in the KeyError are applications in a different model.

Full run attached.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2022-06-22T03:41:20Z
 * owner: [vern](https://launchpad.net/~vern)
 * assignee: [gabrielcocenza](https://launchpad.net/~gabrielcocenza)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1979382)

**Comment by esunar** [comment]
(by [vern](https://launchpad.net/~vern))

**Comment by esunar** [comment]
(by [vern](https://launchpad.net/~vern))

**Comment by esunar** [comment]
(by [vern](https://launchpad.net/~vern))
The attached patch uses the app_to_charm_map.get(app) method instead of app_to_charm_map[app] and ignores mismatches if one of the spaces is XModel (as set by the existing get_relation_space function).
