### ISSUE TITLE
ImportError: No module named 'attr'

### ISSUE THREAD

**Issue by esunar** [esunar/test4#135]
I just installed juju-lint in a clean xenial LXC, and ran juju-lint --help. I got the following output:

ubuntu@juju-lint:~$ juju-lint --help
Traceback (most recent call last):
  File "/usr/bin/juju-lint", line 9, in <module>
    load_entry_point('juju-lint===1.0.0.dev1-201807241352-ubuntu16.04.1', 'console_scripts', 'juju-lint')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/jujulint.py", line 13, in <module>
    from attr import attrs, attrib
ImportError: No module named 'attr'

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2018-07-25T07:52:08Z
 * owner: [mthaddon](https://launchpad.net/~mthaddon)
 * assignee: [stub](https://launchpad.net/~stub)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1783501)

**Comment by esunar** [comment]
(by [stub](https://launchpad.net/~stub))
This is the deb package install. We need to package attrs into the PPA.

**Comment by esunar** [comment]
(by [stub](https://launchpad.net/~stub))
https://code.launchpad.net/~stub/juju-lint/+git/juju-lint/+merge/350926
