### ISSUE TITLE
juju-lint does not support Kubernetes deployment

### ISSUE THREAD

**Issue by esunar** [esunar/test4#137]
I ran this on K8s deployed but it seems this tool does not support it. This bug is file to request to support the same.

ubuntu@ip-172-25-11-169:~$ juju-lint -c  /snap/juju-lint/6/contrib/canonical-openstack-rules.yaml /tmp/juju-status.json
2018-11-29 17:08:54 [ERROR] charm 'aws-integrator' not recognised
2018-11-29 17:08:54 [ERROR] charm 'kubeapi-load-balancer' not recognised
2018-11-29 17:08:54 [ERROR] charm 'kubernetes-master' not recognised
2018-11-29 17:08:54 [ERROR] charm 'canal' not recognised
2018-11-29 17:08:54 [ERROR] charm 'kubernetes-worker' not recognised
2018-11-29 17:08:54 [ERROR] charm 'apache2' not recognised
2018-11-29 17:08:54 [ERROR] ops charm 'landscape-server' not found
2018-11-29 17:08:54 [ERROR] ops charm 'openstack-service-checks' not found
2018-11-29 17:08:54 [ERROR] ops charm 'prometheus-openstack-exporter' not found
2018-11-29 17:08:54 [ERROR] ops charm 'prometheus-ceph-exporter' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'ceilometer' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'ceilometer-agent' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'ceph-mon' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'ceph-osd' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'cinder' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'cinder-ceph' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'glance' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'heat' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'keystone' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'neutron-api' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'neutron-openvswitch' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'nova-cloud-controller' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'nova-compute' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'openstack-dashboard' not found
2018-11-29 17:08:54 [ERROR] Application landscape-client has status 'maintenance' (since: 28 Nov 2018 20:30:34Z, message: Need computer-title and juju-info to proceed); {We expected: ['active', 'unknown']}
2018-11-29 17:08:54 [INFO] The following subordinates couldn't be found:
2018-11-29 17:08:54 [ERROR]  -> landscape-client [aws-integrator, nagios]
2018-11-29 17:08:54 [ERROR]  -> nrpe [aws-integrator, nagios]
2018-11-29 17:08:54 [ERROR]  -> canonical-livepatch [apache2, aws-integrator, elasticsearch, grafana, graylog, kubeapi-load-balancer, kubernetes-master, kubernetes-worker, mongodb, nagios, prometheus]
2018-11-29 17:08:54 [ERROR]  -> filebeat [apache2, aws-integrator, easyrsa, elasticsearch, etcd, grafana, kubeapi-load-balancer, mongodb, prometheus]
2018-11-29 17:08:54 [ERROR]  -> ntp [apache2, aws-integrator, elasticsearch, grafana, graylog, kubeapi-load-balancer, kubernetes-master, kubernetes-worker, mongodb, nagios, prometheus]
2018-11-29 17:08:54 [ERROR]  -> telegraf [apache2, aws-integrator, easyrsa, elasticsearch, etcd, grafana, graylog, kubeapi-load-balancer, mongodb]
2018-11-29 17:08:54 [ERROR]  -> thruk-agent [nagios]
ubuntu@ip-172-25-11-169:~$

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2018-11-29T17:12:29Z
 * owner: [narindergupta](https://launchpad.net/~narindergupta)
 * assignee: [sbparke](https://launchpad.net/~sbparke)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1805875)

**Comment by esunar** [comment]
(by [chris.sanders](https://launchpad.net/~chris.sanders))
For clarity, not all of the above errors should be suppressed. Only the following are 'incorrect' for a K8's deploy (on AWS).

2018-11-29 17:08:54 [ERROR] charm 'aws-integrator' not recognised
2018-11-29 17:08:54 [ERROR] charm 'kubeapi-load-balancer' not recognised
2018-11-29 17:08:54 [ERROR] charm 'kubernetes-master' not recognised
2018-11-29 17:08:54 [ERROR] charm 'canal' not recognised
2018-11-29 17:08:54 [ERROR] charm 'kubernetes-worker' not recognised
2018-11-29 17:08:54 [ERROR] charm 'apache2' not recognised
2018-11-29 17:08:54 [ERROR] ops charm 'landscape-server' not found
2018-11-29 17:08:54 [ERROR] ops charm 'openstack-service-checks' not found
2018-11-29 17:08:54 [ERROR] ops charm 'prometheus-openstack-exporter' not found
2018-11-29 17:08:54 [ERROR] ops charm 'prometheus-ceph-exporter' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'ceilometer' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'ceilometer-agent' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'ceph-mon' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'ceph-osd' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'cinder' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'cinder-ceph' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'glance' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'heat' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'keystone' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'neutron-api' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'neutron-openvswitch' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'nova-cloud-controller' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'nova-compute' not found
2018-11-29 17:08:54 [ERROR] OpenStack charm 'openstack-dashboard' not found

**Comment by esunar** [comment]
(by [niedbalski](https://launchpad.net/~niedbalski))
This doesn't works on kubernetes as no k8s mandatory checks are on place in the contrib canonical rules.

Traceback (most recent call last):
  File "/snap/juju-lint/25/bin/juju-lint", line 33, in <module>
    sys.exit(load_entry_point('jujulint==1.0.2.dev7+g39fd901', 'console_scripts', 'juju-lint')())
  File "/snap/juju-lint/25/lib/python3.6/site-packages/jujulint/cli.py", line 147, in main
    cli.audit_file(manual_file, cloud_type=manual_type)
  File "/snap/juju-lint/25/lib/python3.6/site-packages/jujulint/cli.py", line 77, in audit_file
    linter.lint_yaml_file(filename)
  File "/snap/juju-lint/25/lib/python3.6/site-packages/jujulint/lint.py", line 881, in lint_yaml_file
    return self.do_lint(parsed_yaml)
  File "/snap/juju-lint/25/lib/python3.6/site-packages/jujulint/lint.py", line 904, in do_lint
    self.check_charms()
  File "/snap/juju-lint/25/lib/python3.6/site-packages/jujulint/lint.py", line 619, in check_charms
    for charm in self.lint_rules["kubernetes mandatory"]:
KeyError: 'kubernetes mandatory'

**Comment by esunar** [comment]
(by [sbparke](https://launchpad.net/~sbparke))
Fix Merged to main branch
